// Manual price overlay for delisted/acquired tickers Yahoo has purged (so the index
// stops silently dropping them — see data/manual_prices.csv, generated by
// scripts/genManualPrices.mjs). Fill the `close` column there; this reads it back.
//
// CSV columns: ticker,date,close,role,company,event_or_note
//   - a normal row supplies the close on a specific date (entry/exit lookups)
//   - a row with date == "DELIST" supplies the deal/delisting price, used to mark a
//     STILL-OPEN position to its buyout value instead of dropping it (priceLatest).
// Blank/zero closes are ignored, so a half-filled file is safe — it just prices what
// it can. Consulted BEFORE Yahoo in priceCache, so a known-dead ticker costs no fetch.

import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { canonicalTicker } from './tickerAliases.js';

const FILE = join(dirname(fileURLToPath(import.meta.url)), '..', 'data', 'manual_prices.csv');
const NEAR_DAYS = 10; // match priceCache's on-or-after window

let TABLE = null; // canonicalTicker -> { d: Map<date,close>, sorted: [[date,close]], latest: number|null }

async function load() {
  if (TABLE) return TABLE;
  TABLE = {};
  let text;
  try {
    text = await readFile(FILE, 'utf8');
  } catch {
    return TABLE; // no overlay file -> empty (no-op)
  }
  const lines = text.split(/\r?\n/);
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    // ticker/date/close never contain commas, so a plain split on the first fields is safe.
    const parts = lines[i].split(',');
    const tk = (parts[0] || '').trim().toUpperCase();
    const date = (parts[1] || '').trim();
    const close = Number((parts[2] || '').trim());
    if (!tk || !date || !Number.isFinite(close) || close <= 0) continue;
    const key = canonicalTicker(tk);
    if (!TABLE[key]) TABLE[key] = { d: new Map(), sorted: [], latest: null };
    if (date.toUpperCase() === 'DELIST') TABLE[key].latest = close;
    else TABLE[key].d.set(date, close);
  }
  for (const e of Object.values(TABLE)) {
    e.sorted = [...e.d.entries()].sort((a, b) => a[0].localeCompare(b[0]));
    if (e.latest == null && e.sorted.length) e.latest = e.sorted[e.sorted.length - 1][1]; // fallback: last known close
  }
  return TABLE;
}

// Manual close on/just-after `date` (exact, else nearest filled date within NEAR_DAYS). null if none.
export async function manualClose(ticker, date) {
  const e = (await load())[canonicalTicker(ticker)];
  if (!e) return null;
  if (e.d.has(date)) return e.d.get(date);
  const start = Date.parse(`${date}T00:00:00Z`);
  for (const [d, c] of e.sorted) {
    if (d >= date) return (Date.parse(`${d}T00:00:00Z`) - start) / 86400000 <= NEAR_DAYS ? c : null;
  }
  return null;
}

// Deal/delisting price for a dead ticker — used to close a still-open position. null if none.
export async function manualLatest(ticker) {
  const e = (await load())[canonicalTicker(ticker)];
  return e ? e.latest : null;
}

// CLI: `node src/manualPrices.js` — summarize how many cells are filled.
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('manualPrices.js')) {
  const t = await load();
  const tickers = Object.keys(t);
  let cells = 0, withLatest = 0;
  for (const e of Object.values(t)) {
    cells += e.d.size;
    if (e.latest != null) withLatest++;
  }
  console.log(`manual overlay: ${tickers.length} tickers, ${cells} date-closes filled, ${withLatest} with a deal/latest price`);
}
